/** 唯一内部内容合同；renderSkin 为 render-only 引用，永不进入 World/hash。 */
export type RhetoricResourceId = 'progress' | 'pressure' | 'focus';
export type RhetoricEffect = Readonly<{ kind: 'modify-resource'; targetId: RhetoricResourceId; op: 'add' | 'set'; value: number }>;
export type RhetoricCard = Readonly<{ cardId: string; displayName: string; flavorText: string; focusCost: number; maxCopies: number; skinKey: string; effects: readonly RhetoricEffect[] }>;
export type RhetoricDeckEntry = Readonly<{ cardId: string; copies: number }>;
export type RhetoricIntent = Readonly<{ id: string; label: string; preview: string; effects: readonly RhetoricEffect[] }>;
export type RhetoricEncounter = Readonly<{ encounterId: string; opponentId: string; displayName: string; opponentSubtitle: string; objective: string; target: number; pressureLimit: number; turnLimit: number; openingHand: number; drawPerTurn: number; handLimit: number; focusPerTurn: number; backgroundSkinKey: string; portraitSkinKey: string; intentions: readonly RhetoricIntent[] }>;
export type RhetoricRenderSkin = Readonly<{ id: string; cardSkinPrefix: string; backgroundSkinKey: string; portraitSkinKey: string }>;
export type RhetoricGameConfig = Readonly<{ catalogVersion: 1; seed: number; deck: readonly RhetoricDeckEntry[]; encounter: RhetoricEncounter; renderSkin: RhetoricRenderSkin }>;

export const RHETORIC_CATALOG_VERSION = 1 as const;
export const RHETORIC_CATALOG: readonly RhetoricCard[] = [
  { cardId: 'probe-question', displayName: '试探提问', flavorText: '先让他把话说完整。', focusCost: 1, maxCopies: 3, skinKey: 'game-rhetoric-duel/card/probe-question', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 1 }] },
  { cardId: 'pin-down-detail', displayName: '钉住细节', flavorText: '那就请你把这一处说清。', focusCost: 2, maxCopies: 2, skinKey: 'game-rhetoric-duel/card/pin-down-detail', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 3 }] },
  { cardId: 'steady-breath', displayName: '稳住呼吸', flavorText: '别急，先把气息稳下来。', focusCost: 1, maxCopies: 2, skinKey: 'game-rhetoric-duel/card/steady-breath', effects: [{ kind: 'modify-resource', targetId: 'pressure', op: 'add', value: -2 }] },
  { cardId: 'catch-the-thread', displayName: '接住话头', flavorText: '这句话，恰好说明了问题。', focusCost: 1, maxCopies: 2, skinKey: 'game-rhetoric-duel/card/catch-the-thread', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 1 }, { kind: 'modify-resource', targetId: 'pressure', op: 'add', value: -1 }] },
  { cardId: 'press-the-point', displayName: '连环诘问', flavorText: '一个问题答完，再答下一个。', focusCost: 3, maxCopies: 1, skinKey: 'game-rhetoric-duel/card/press-the-point', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 4 }] },
  { cardId: 'reframe-the-case', displayName: '换位陈述', flavorText: '若换作是你，也会这样选吗？', focusCost: 2, maxCopies: 2, skinKey: 'game-rhetoric-duel/card/reframe-the-case', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 2 }, { kind: 'modify-resource', targetId: 'pressure', op: 'add', value: -1 }] },
  { cardId: 'state-the-line', displayName: '直陈底线', flavorText: '此事没有退让的余地。', focusCost: 2, maxCopies: 1, skinKey: 'game-rhetoric-duel/card/state-the-line', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 3 }, { kind: 'modify-resource', targetId: 'pressure', op: 'add', value: 1 }] },
  { cardId: 'hold-the-answer', displayName: '暂缓回应', flavorText: '不必急着接下这句话。', focusCost: 0, maxCopies: 2, skinKey: 'game-rhetoric-duel/card/hold-the-answer', effects: [{ kind: 'modify-resource', targetId: 'pressure', op: 'add', value: -1 }] },
  { cardId: 'gather-your-thoughts', displayName: '整理思路', flavorText: '把散乱的念头排成一线。', focusCost: 0, maxCopies: 1, skinKey: 'game-rhetoric-duel/card/gather-your-thoughts', effects: [{ kind: 'modify-resource', targetId: 'focus', op: 'add', value: 1 }] },
  { cardId: 'close-the-argument', displayName: '收束论点', flavorText: '所有证词，都指向同一个答案。', focusCost: 2, maxCopies: 1, skinKey: 'game-rhetoric-duel/card/close-the-argument', effects: [{ kind: 'modify-resource', targetId: 'progress', op: 'add', value: 3 }] },
] as const;

export const STARTER_CALM_REASON: readonly RhetoricDeckEntry[] = [
  { cardId: 'probe-question', copies: 2 }, { cardId: 'pin-down-detail', copies: 2 }, { cardId: 'steady-breath', copies: 2 }, { cardId: 'catch-the-thread', copies: 2 }, { cardId: 'press-the-point', copies: 1 }, { cardId: 'reframe-the-case', copies: 2 }, { cardId: 'state-the-line', copies: 1 }, { cardId: 'hold-the-answer', copies: 1 }, { cardId: 'gather-your-thoughts', copies: 1 }, { cardId: 'close-the-argument', copies: 1 },
] as const;

const effect = (targetId: RhetoricResourceId, value: number): RhetoricEffect => ({ kind: 'modify-resource', targetId, op: 'add', value });
const encounter = (encounterId: string, displayName: string, objective: string, target: number, pressureLimit: number, focusPerTurn: number, opponent: Readonly<{ id: string; name: string; subtitle: string; portraitSkinKey: string }>, backgroundSkinKey: string, intentions: readonly Readonly<[string, string, string, number]>[]): RhetoricEncounter => ({ encounterId, opponentId: opponent.id, displayName: opponent.name, opponentSubtitle: opponent.subtitle, objective, target, pressureLimit, turnLimit: 4, openingHand: 5, drawPerTurn: 3, handLimit: 6, focusPerTurn, backgroundSkinKey, portraitSkinKey: opponent.portraitSkinKey, intentions: intentions.map(([intentId, label, preview, pressure]) => ({ id: intentId, label, preview, effects: [effect('pressure', pressure)] })) });
export const RHETORIC_ENCOUNTERS: readonly RhetoricEncounter[] = [
  encounter('gatekeeper-shi', '旧巷之门', '让石七打开被私占的巷门', 10, 10, 3, { id: 'shi', name: '石七', subtitle: '旧巷守门人', portraitSkinKey: 'game-rhetoric-duel/opponent/shi' }, 'game-rhetoric-duel/background/old-alley', [['cold-question', '冷声质问', '“你凭什么要我开门？”', 1], ['raise-the-bar', '抬高门槛', '“规矩不是为你一个人改的。”', 2], ['public-ridicule', '当众讥讽', '“说得好听，旁人可未必信。”', 2], ['final-refusal', '最后拒绝', '“再纠缠，我便叫人送客。”', 3]]),
  encounter('merchant-luo', '药铺旧约', '说服罗掌柜兑现先前的口头约定', 11, 9, 3, { id: 'luo', name: '罗掌柜', subtitle: '精于算计的商人', portraitSkinKey: 'game-rhetoric-duel/opponent/luo' }, 'game-rhetoric-duel/background/apothecary', [['count-the-cost', '盘算得失', '“这笔账，究竟谁来承担？”', 1], ['test-the-price', '抬价试探', '“你想要的，总得拿出相称的东西。”', 2], ['seize-a-flaw', '揪住细节', '“这一句前后不一，你如何解释？”', 2], ['close-the-ledger', '合账送客', '“账已算完，今日便到这里。”', 2]]),
  encounter('instructor-jiang', '讲堂论策', '让姜教习承认处置方案可行', 12, 10, 4, { id: 'jiang', name: '姜教习', subtitle: '严厉的见证人', portraitSkinKey: 'game-rhetoric-duel/opponent/jiang' }, 'game-rhetoric-duel/background/lecture-hall', [['formal-challenge', '先礼后问', '“先说说，你的依据从何而来。”', 1], ['rapid-cross-exam', '连番追问', '“这一点尚未回答。下一点呢？”', 2], ['attack-the-weakness', '攻其短处', '“你的方案，最经不起推敲的正是这里。”', 3], ['final-judgment', '当场裁断', '“给你最后一次机会，说服我。”', 2]]),
] as const;
export const DEFAULT_RHETORIC_ENCOUNTER = RHETORIC_ENCOUNTERS[0];
export const RHETORIC_FIXTURES: readonly RhetoricGameConfig[] = RHETORIC_ENCOUNTERS.map((encounter, index) => ({ catalogVersion: 1, seed: 7 + index, deck: STARTER_CALM_REASON, encounter, renderSkin: { id: `game-rhetoric-duel/duel/${encounter.encounterId}`, cardSkinPrefix: 'game-rhetoric-duel/card/', backgroundSkinKey: encounter.backgroundSkinKey, portraitSkinKey: encounter.portraitSkinKey } }));
export const DEFAULT_RHETORIC_CONFIG = RHETORIC_FIXTURES[0];

const fail = (path: string, message: string): never => { throw new Error(`Invalid RhetoricGameConfig: ${path} ${message}`); };
const record = (value: unknown, path: string): Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : fail(path, 'must be an object');
const text = (value: unknown, path: string): string => typeof value === 'string' && value.trim().length > 0 ? value : fail(path, 'must be a non-empty string');
const integer = (value: unknown, path: string, min: number, max = 1000): number => typeof value === 'number' && Number.isSafeInteger(value) && value >= min && value <= max ? value : fail(path, `must be an integer in ${min}..${max}`);
const unique = (values: readonly string[], path: string): void => { if (new Set(values).size !== values.length) fail(path, 'must be unique'); };
function parseEffect(value: unknown, path: string): RhetoricEffect { const raw = record(value, path); if (raw.kind !== 'modify-resource') fail(`${path}.kind`, 'is not approved'); if (raw.targetId !== 'progress' && raw.targetId !== 'pressure' && raw.targetId !== 'focus') fail(`${path}.targetId`, 'is not approved'); if (raw.op !== 'add' && raw.op !== 'set') fail(`${path}.op`, 'is not approved'); return { kind: 'modify-resource', targetId: raw.targetId as RhetoricResourceId, op: raw.op as 'add' | 'set', value: integer(raw.value, `${path}.value`, -100, 100) }; }

/** Strict boundary shared by internal preview fixtures and a future export adapter. */
export function validateRhetoricGameConfig(value: unknown, catalog: readonly RhetoricCard[] = RHETORIC_CATALOG): RhetoricGameConfig {
  if (catalog.length !== 10) fail('catalog', 'must contain exactly 10 cards'); unique(catalog.map((card) => card.cardId), 'catalog.cardId'); unique(catalog.map((card) => card.skinKey), 'catalog.skinKey');
  const cards = new Map(catalog.map((card, index) => { text(card.cardId, `catalog[${index}].cardId`); text(card.displayName, `catalog[${index}].displayName`); text(card.flavorText, `catalog[${index}].flavorText`); text(card.skinKey, `catalog[${index}].skinKey`); if (card.skinKey !== `game-rhetoric-duel/card/${card.cardId}`) fail(`catalog[${index}].skinKey`, 'must equal game-rhetoric-duel/card/<cardId>'); integer(card.focusCost, `catalog[${index}].focusCost`, 0, 20); integer(card.maxCopies, `catalog[${index}].maxCopies`, 1, 20); if (!Array.isArray(card.effects) || card.effects.length === 0) fail(`catalog[${index}].effects`, 'must be non-empty'); card.effects.forEach((entry, effectIndex) => parseEffect(entry, `catalog[${index}].effects[${effectIndex}]`)); return [card.cardId, card] as const; }));
  const raw = record(value, 'config'); if (integer(raw.catalogVersion, 'config.catalogVersion', 1, 1) !== RHETORIC_CATALOG_VERSION) fail('config.catalogVersion', 'is unsupported');
  const deckRaw = Array.isArray(raw.deck) && raw.deck.length > 0 ? raw.deck : fail('config.deck', 'must be non-empty'); const deck = deckRaw.map((entry, index) => { const row = record(entry, `config.deck[${index}]`); const cardId = text(row.cardId, `config.deck[${index}].cardId`); const card = cards.get(cardId); if (!card) return fail(`config.deck[${index}].cardId`, 'is unknown'); return { cardId, copies: integer(row.copies, `config.deck[${index}].copies`, 1, card.maxCopies) }; }); unique(deck.map((entry) => entry.cardId), 'config.deck.cardId');
  const enc = record(raw.encounter, 'config.encounter'); const handLimit = integer(enc.handLimit, 'config.encounter.handLimit', 1, 20); const turnLimit = integer(enc.turnLimit, 'config.encounter.turnLimit', 1, 20); const intentionsRaw = Array.isArray(enc.intentions) && enc.intentions.length >= turnLimit ? enc.intentions : fail('config.encounter.intentions', 'must cover turnLimit');
  const intentions = intentionsRaw.map((entry, index) => { const intent = record(entry, `config.encounter.intentions[${index}]`); const effects = Array.isArray(intent.effects) && intent.effects.length > 0 ? intent.effects.map((effectValue, effectIndex) => parseEffect(effectValue, `config.encounter.intentions[${index}].effects[${effectIndex}]`)) : fail(`config.encounter.intentions[${index}].effects`, 'must be non-empty'); return { id: text(intent.id, `config.encounter.intentions[${index}].id`), label: text(intent.label, `config.encounter.intentions[${index}].label`), preview: text(intent.preview, `config.encounter.intentions[${index}].preview`), effects }; }); unique(intentions.map((intent) => intent.id), 'config.encounter.intentions.id');
  const encounter: RhetoricEncounter = { encounterId: text(enc.encounterId, 'config.encounter.encounterId'), opponentId: text(enc.opponentId, 'config.encounter.opponentId'), displayName: text(enc.displayName, 'config.encounter.displayName'), opponentSubtitle: text(enc.opponentSubtitle, 'config.encounter.opponentSubtitle'), objective: text(enc.objective, 'config.encounter.objective'), target: integer(enc.target, 'config.encounter.target', 1), pressureLimit: integer(enc.pressureLimit, 'config.encounter.pressureLimit', 1), turnLimit, openingHand: integer(enc.openingHand, 'config.encounter.openingHand', 1, handLimit), drawPerTurn: integer(enc.drawPerTurn, 'config.encounter.drawPerTurn', 1, handLimit), handLimit, focusPerTurn: integer(enc.focusPerTurn, 'config.encounter.focusPerTurn', 0, 20), backgroundSkinKey: text(enc.backgroundSkinKey, 'config.encounter.backgroundSkinKey'), portraitSkinKey: text(enc.portraitSkinKey, 'config.encounter.portraitSkinKey'), intentions };
  const render = record(raw.renderSkin, 'config.renderSkin'); const renderSkin = { id: text(render.id, 'config.renderSkin.id'), cardSkinPrefix: text(render.cardSkinPrefix, 'config.renderSkin.cardSkinPrefix'), backgroundSkinKey: text(render.backgroundSkinKey, 'config.renderSkin.backgroundSkinKey'), portraitSkinKey: text(render.portraitSkinKey, 'config.renderSkin.portraitSkinKey') }; if (renderSkin.backgroundSkinKey !== encounter.backgroundSkinKey || renderSkin.portraitSkinKey !== encounter.portraitSkinKey) fail('config.renderSkin', 'must match encounter skin keys');
  return { catalogVersion: 1, seed: integer(raw.seed, 'config.seed', 0, 0xffffffff), deck, encounter, renderSkin };
}
