// 生成文件 · 勿手改 —— npx vite-node scripts/gen-capability-registry.mjs（P2e 懒能力注册表）
// 行式契约：每个能力恰占一行 `  { id: '…', provides: […], load: () => import('…').then((m) => m.xxx) },`
// ——vite.config.cartridge.ts 的子集插件按行过滤本文件、只留 manifest 用到的能力，rollup 据此摇树。
// 顺序 = 静态注册表 ALL_CAPABILITIES 登记序（迁移期冻结·capability-registry.gen.test 对拍）。
import type { CapabilityLoader } from './capability-index.js';

export const CAPABILITY_LOADERS: readonly CapabilityLoader[] = [
  { id: 'a1-transform', provides: ['Transform'], load: () => import('@atom-skills/transform/index.js').then((m) => m.transformCapability) },
  { id: 'a2-hierarchy', provides: ['Hierarchy'], load: () => import('@atom-skills/hierarchy/index.js').then((m) => m.hierarchyCapability) },
  { id: 'b1-velocity', provides: ['Velocity'], load: () => import('@atom-skills/velocity/index.js').then((m) => m.velocityCapability) },
  { id: 'b2-acceleration', provides: ['Acceleration'], load: () => import('@atom-skills/acceleration/index.js').then((m) => m.accelerationCapability) },
  { id: 'b3-mass', provides: ['Mass'], load: () => import('@atom-skills/mass/index.js').then((m) => m.massCapability) },
  { id: 'c1-shape', provides: ['Shape'], load: () => import('@atom-skills/shape/index.js').then((m) => m.shapeCapability) },
  { id: 'd1-overlap-detect', provides: ['Overlap'], load: () => import('@atom-skills/overlap-detect/index.js').then((m) => m.overlapDetectCapability) },
  { id: 'd1-overlap-detect-3d', provides: ['Collider3D', 'Overlap3D'], load: () => import('@atom-skills/overlap-detect-3d/index.js').then((m) => m.overlapDetect3dCapability) },
  { id: 'd2-navmesh-bake', provides: ['NavMesh'], load: () => import('@atom-skills/navmesh-bake/index.js').then((m) => m.navmeshBakeCapability) },
  { id: 'd-collision-resolve-3d', provides: [], load: () => import('@atom-skills/collision-resolve-3d/index.js').then((m) => m.collisionResolve3dCapability) },
  { id: 'e1-timer', provides: ['Timer', 'TimerDone'], load: () => import('@atom-skills/timer/index.js').then((m) => m.timerCapability) },
  { id: 'f1-resource', provides: ['Resource', 'ResourceModify'], load: () => import('@atom-skills/resource/index.js').then((m) => m.resourceCapability) },
  { id: 'f2-flag', provides: ['Flag'], load: () => import('@atom-skills/flag/index.js').then((m) => m.flagCapability) },
  { id: 'g1-tag', provides: ['Tag'], load: () => import('@atom-skills/tag/index.js').then((m) => m.tagCapability) },
  { id: 'g2-relation', provides: ['Relation'], load: () => import('@atom-skills/relation/index.js').then((m) => m.relationCapability) },
  { id: 'g3-owner', provides: ['Owner'], load: () => import('@atom-skills/owner/index.js').then((m) => m.ownerCapability) },
  { id: 'g4-group', provides: ['Group'], load: () => import('@atom-skills/group/index.js').then((m) => m.groupCapability) },
  { id: 'h1-visibility', provides: ['Visibility'], load: () => import('@atom-skills/visibility/index.js').then((m) => m.visibilityCapability) },
  { id: 'i1-input-capture', provides: ['InputQueue', 'RawInput'], load: () => import('@atom-skills/input-capture/index.js').then((m) => m.inputCaptureCapability) },
  { id: 'i2-action-map', provides: ['Action'], load: () => import('@atom-skills/action-map/index.js').then((m) => m.actionMapCapability) },
  { id: 'i3-controllable', provides: ['Controllable'], load: () => import('@atom-skills/controllable/index.js').then((m) => m.controllableCapability) },
  { id: 'j1-state', provides: ['State', 'StateChanged'], load: () => import('@atom-skills/state/index.js').then((m) => m.stateCapability) },
  { id: 'k1-spawn', provides: ['SpawnRequest'], load: () => import('@atom-skills/spawn/index.js').then((m) => m.spawnCapability) },
  { id: 'k2-destroy', provides: ['DestroyRequest'], load: () => import('@atom-skills/destroy/index.js').then((m) => m.destroyCapability) },
  { id: 'l1-sprite', provides: ['Sprite'], load: () => import('@atom-skills/sprite/index.js').then((m) => m.spriteCapability) },
  { id: 'l2-color', provides: ['Color'], load: () => import('@atom-skills/color/index.js').then((m) => m.colorCapability) },
  { id: 'l3-frame', provides: ['Frame'], load: () => import('@atom-skills/frame/index.js').then((m) => m.frameCapability) },
  { id: 'l4-sound', provides: ['Sound'], load: () => import('@atom-skills/sound/index.js').then((m) => m.soundCapability) },
  { id: 'l5-camera', provides: ['Camera'], load: () => import('@atom-skills/camera/index.js').then((m) => m.cameraCapability) },
  { id: 'l6-text', provides: ['Text'], load: () => import('@atom-skills/text/index.js').then((m) => m.textCapability) },
  { id: 'w1-random', provides: ['RandomSeed'], load: () => import('@atom-skills/random/index.js').then((m) => m.randomCapability) },
  { id: 'w2-spatial-query', provides: ['SpatialIndex'], load: () => import('@atom-skills/spatial-query/index.js').then((m) => m.spatialQueryCapability) },
  { id: 'l7-vfx2d', provides: ['Vfx2D'], load: () => import('@atom-skills/vfx2d/index.js').then((m) => m.vfx2dCapability) },
  { id: 'x3-string-variable', provides: ['StringVar', 'StringSet'], load: () => import('@atom-skills/string-variable/index.js').then((m) => m.stringVariableCapability) },
  { id: 't1-motion-apply', provides: [], load: () => import('@skills/tier1/motion-apply.js').then((m) => m.motionApplyCapability) },
  { id: 't1-accel-apply', provides: [], load: () => import('@skills/tier1/accel-apply.js').then((m) => m.accelApplyCapability) },
  { id: 't1-lifetime', provides: [], load: () => import('@skills/tier1/lifetime.js').then((m) => m.lifetimeCapability) },
  { id: 't1-rotation-apply', provides: [], load: () => import('@skills/tier1/rotation-apply.js').then((m) => m.rotationApplyCapability) },
  { id: 't1-animation', provides: [], load: () => import('@skills/tier1/animation.js').then((m) => m.animationCapability) },
  { id: 't1-hierarchy-resolve', provides: [], load: () => import('@skills/tier1/hierarchy-resolve.js').then((m) => m.hierarchyResolveCapability) },
  { id: 't1-hierarchy-cascade', provides: [], load: () => import('@skills/tier1/hierarchy-cascade.js').then((m) => m.hierarchyCascadeCapability) },
  { id: 't1-tween', provides: ['Tween'], load: () => import('@skills/tier1/tween.js').then((m) => m.tweenCapability) },
  { id: 't1-group-gc', provides: [], load: () => import('@skills/tier1/group-gc.js').then((m) => m.groupGcCapability) },
  { id: 't2-collision-resolve', provides: [], load: () => import('@skills/tier2/collision-resolve.js').then((m) => m.collisionResolveCapability) },
  { id: 't2-ground-sense', provides: ['Grounded'], load: () => import('@skills/tier2/ground-sense.js').then((m) => m.groundSenseCapability) },
  { id: 't2-jump', provides: [], load: () => import('@skills/tier2/jump.js').then((m) => m.jumpCapability) },
  { id: 't2-bounds-clamp', provides: ['Bounds'], load: () => import('@skills/tier2/bounds-clamp.js').then((m) => m.boundsClampCapability) },
  { id: 't2-trigger-zone', provides: ['Sensor', 'Trigger'], load: () => import('@skills/tier2/trigger-zone.js').then((m) => m.triggerZoneCapability) },
  { id: 't2-friction', provides: [], load: () => import('@skills/tier2/friction.js').then((m) => m.frictionCapability) },
  { id: 't2-event-when', provides: ['EventWhen', 'Signal'], load: () => import('@skills/tier2/event-when.js').then((m) => m.eventWhenCapability) },
  { id: 't2-effect-apply', provides: ['Effect'], load: () => import('@skills/tier2/effect-apply.js').then((m) => m.effectApplyCapability) },
  { id: 't2-camera-follow', provides: ['CameraTarget'], load: () => import('@skills/tier2/camera-follow.js').then((m) => m.cameraFollowCapability) },
  { id: 't2-clickable', provides: ['Clickable'], load: () => import('@skills/tier2/clickable.js').then((m) => m.clickableCapability) },
  { id: 't2-craft-recipe', provides: ['CraftRecipe'], load: () => import('@skills/tier2/craft-recipe.js').then((m) => m.craftRecipeCapability) },
  { id: 't2-merge-on-place', provides: ['MergeEvent', 'MergeDrop'], load: () => import('@skills/tier2/merge-on-place.js').then((m) => m.mergeOnPlaceCapability) },
  { id: 't2-order-fulfill', provides: ['Order', 'DeliverDrop'], load: () => import('@skills/tier2/order-fulfill.js').then((m) => m.orderFulfillCapability) },
  { id: 't2-merge-proximity-clear', provides: ['Blocker', 'MergeProximity'], load: () => import('@skills/tier2/merge-proximity-clear.js').then((m) => m.mergeProximityClearCapability) },
  { id: 't2-zone-occupancy', provides: ['Zone'], load: () => import('@skills/tier2/zone-occupancy.js').then((m) => m.zoneOccupancyCapability) },
  { id: 't2-hitbox', provides: ['Hitbox', 'Status'], load: () => import('@skills/tier2/hitbox.js').then((m) => m.hitboxCapability) },
  { id: 't2-over-time', provides: ['OverTime'], load: () => import('@skills/tier2/over-time.js').then((m) => m.overTimeCapability) },
  { id: 't2-mortal', provides: ['Mortal'], load: () => import('@skills/tier2/mortal.js').then((m) => m.mortalCapability) },
  { id: 't2-steering', provides: ['Steering'], load: () => import('@skills/tier2/steering.js').then((m) => m.steeringCapability) },
  { id: 't2-keybind', provides: ['KeyBinding'], load: () => import('@skills/tier2/keybind.js').then((m) => m.keybindCapability) },
  { id: 't2-stats', provides: ['Stats'], load: () => import('@skills/tier2/stats.js').then((m) => m.statsCapability) },
  { id: 't2-launch', provides: ['Launch'], load: () => import('@skills/tier2/launch.js').then((m) => m.launchCapability) },
  { id: 't2-tilemap', provides: ['Tilemap'], load: () => import('@skills/tier2/tilemap.js').then((m) => m.tilemapCapability) },
  { id: 't2-anim-state', provides: ['AnimState'], load: () => import('@skills/tier2/anim-state.js').then((m) => m.animStateCapability) },
  { id: 't2-facing', provides: ['Facing'], load: () => import('@skills/tier2/facing.js').then((m) => m.facingCapability) },
  { id: 't2-face-rotate', provides: ['FaceRotate', 'FaceDir'], load: () => import('@skills/tier2/face-rotate.js').then((m) => m.faceRotateCapability) },
  { id: 't2-card-play', provides: [], load: () => import('@skills/tier2/card-play.js').then((m) => m.cardPlayCapability) },
  { id: 't2-dice-roll', provides: ['DicePool', 'RolledDice'], load: () => import('@skills/tier2/dice-roll.js').then((m) => m.diceRollCapability) },
  { id: 't2-card-pile', provides: ['CardPile'], load: () => import('@skills/tier2/card-pile.js').then((m) => m.cardPileCapability) },
  { id: 't2-identity-card-play', provides: ['CardCatalog', 'IdentityCardPile', 'IdentityCardCommand', 'IdentityCardDrawCommand'], load: () => import('@skills/tier2/identity-card-play.js').then((m) => m.identityCardPlayCapability) },
  { id: 't2-self-rule', provides: ['SelfRule'], load: () => import('@skills/tier2/self-rule.js').then((m) => m.selfRuleCapability) },
  { id: 't2-group-count', provides: ['GroupCount'], load: () => import('@skills/tier2/group-count.js').then((m) => m.groupCountCapability) },
  { id: 't2-grid-move', provides: ['HexBoard', 'HexPos', 'GridMover'], load: () => import('@skills/tier2/grid-move.js').then((m) => m.gridMoveCapability) },
  { id: 't2-pathfind', provides: ['NavGraph', 'NavAgent', 'NavPath'], load: () => import('@skills/tier2/pathfind.js').then((m) => m.pathfindCapability) },
  { id: 't2-gauge', provides: ['Gauge'], load: () => import('@skills/tier2/gauge.js').then((m) => m.gaugeCapability) },
  { id: 't2-text-binding', provides: ['TextBinding'], load: () => import('@skills/tier2/text-binding.js').then((m) => m.textBindingCapability) },
  { id: 't2-drag-place', provides: ['Draggable', 'DropZone'], load: () => import('@skills/tier2/drag-place.js').then((m) => m.dragPlaceCapability) },
  { id: 't2-tray', provides: ['Tray', 'TraySeat'], load: () => import('@skills/tier2/tray.js').then((m) => m.trayCapability) },
  { id: 't2-queue-slots', provides: ['QueueSlots', 'QueueMember'], load: () => import('@skills/tier2/queue-slots.js').then((m) => m.queueSlotsCapability) },
  { id: 't2-grid-drag-square', provides: ['BlockTrayPiece'], load: () => import('@skills/tier2/grid-drag-square.js').then((m) => m.gridDragSquareCapability) },
  { id: 't2-match3-drag-swap', provides: [], load: () => import('@skills/tier2/match3-drag-swap.js').then((m) => m.match3DragSwapCapability) },
  { id: 't2-modifier-stack', provides: ['ModifierSource', 'ModifierTotals'], load: () => import('@skills/tier2/modifier-stack.js').then((m) => m.modifierStackCapability) },
  { id: 't2-behavior-tree', provides: [], load: () => import('@skills/tier2/behavior-tree.js').then((m) => m.behaviorTreeCapability) },
  { id: 't2-orbit-motion', provides: ['Orbit'], load: () => import('@skills/tier2/orbit-motion.js').then((m) => m.orbitMotionCapability) },
  { id: 't2-path-follow', provides: ['PathFollow'], load: () => import('@skills/tier2/path-follow.js').then((m) => m.pathFollowCapability) },
  { id: 't2-flow-field', provides: ['FlowField', 'FlowAgent'], load: () => import('@skills/tier2/flow-field.js').then((m) => m.flowFieldCapability) },
  { id: 't2-stat-bind', provides: ['StatBind'], load: () => import('@skills/tier2/stat-bind.js').then((m) => m.statBindCapability) },
  { id: 't2-bounce-relay', provides: ['Bounce'], load: () => import('@skills/tier2/bounce-relay.js').then((m) => m.bounceRelayCapability) },
  { id: 't2-pull-anchor', provides: ['PullAnchor'], load: () => import('@skills/tier2/pull-anchor.js').then((m) => m.pullAnchorCapability) },
  { id: 't2-weighted-spawn', provides: ['WeightedSpawn'], load: () => import('@skills/tier2/weighted-spawn.js').then((m) => m.weightedSpawnCapability) },
  { id: 't2-matrix-duel', provides: ['DuelMatrix', 'DuelIntent', 'DuelOutcome'], load: () => import('@skills/tier2/matrix-duel.js').then((m) => m.matrixDuelCapability) },
  { id: 't2-turn-order', provides: ['TurnOrder'], load: () => import('@skills/tier2/turn-order.js').then((m) => m.turnOrderCapability) },
  { id: 't2-cooldown', provides: ['Cooldowns'], load: () => import('@skills/tier2/cooldown.js').then((m) => m.cooldownCapability) },
  { id: 't2-damage-table', provides: ['DamageTable', 'Armor'], load: () => import('@skills/tier2/damage-table.js').then((m) => m.damageTableCapability) },
  { id: 't2-inventory', provides: ['Inventory'], load: () => import('@skills/tier2/inventory.js').then((m) => m.inventoryCapability) },
  { id: 't2-conveyor-queue', provides: ['ConveyorQueue'], load: () => import('@skills/tier2/conveyor-queue.js').then((m) => m.conveyorQueueCapability) },
  { id: 't2-memory', provides: ['Memory', 'MemoryRules'], load: () => import('@skills/tier2/memory.js').then((m) => m.memoryCapability) },
  { id: 't2-intent-barrier', provides: ['IntentBarrier', 'IntentInbox'], load: () => import('@skills/tier2/intent-barrier.js').then((m) => m.intentBarrierCapability) },
  { id: 't3-dialogue', provides: ['DialogueScript', 'DialogueAdvance', 'DialogueChoose'], load: () => import('@skills/tier3/dialogue.js').then((m) => m.dialogueCapability) },
  { id: 't3-match3-board', provides: ['MatchBoard', 'BoardCell'], load: () => import('@skills/tier3/match3-board.js').then((m) => m.match3BoardCapability) },
  { id: 't3-prefab', provides: ['PrefabOrigin', 'PrefabLibrary'], load: () => import('@skills/tier3/prefab.js').then((m) => m.prefabCapability) },
  { id: 't3-caster', provides: ['Caster'], load: () => import('@skills/tier3/caster.js').then((m) => m.casterCapability) },
  { id: 't3-aggro', provides: ['Perception'], load: () => import('@skills/tier3/aggro.js').then((m) => m.aggroCapability) },
  { id: 't3-poker-hand', provides: ['PlayedHand', 'PokerHand'], load: () => import('@skills/tier3/poker-hand.js').then((m) => m.pokerHandCapability) },
  { id: 't3-card-scoring', provides: ['PerCardScore', 'PerCardRule', 'PerCardRetrigger'], load: () => import('@skills/tier3/card-scoring.js').then((m) => m.cardScoringCapability) },
  { id: 't3-flow', provides: ['GameFlow'], load: () => import('@skills/tier3/flow.js').then((m) => m.flowCapability) },
  { id: 't3-merge-rule', provides: ['MergeRule'], load: () => import('@skills/tier3/merge-rule.js').then((m) => m.mergeRuleCapability) },
  { id: 't3-timeline', provides: ['Timeline', 'TimelinePlayback'], load: () => import('@skills/tier3/timeline.js').then((m) => m.timelineCapability) },
  { id: 't3-slot-payout', provides: ['SlotMachine', 'LineWins'], load: () => import('@skills/tier3/slot-payout.js').then((m) => m.slotPayoutCapability) },
  { id: 't3-block-grid', provides: ['BlockGrid', 'BoardCell', 'PlaceBlockIntent'], load: () => import('@skills/tier3/block-grid.js').then((m) => m.blockGridCapability) },
  { id: 't3-hand-pattern', provides: [], load: () => import('@skills/tier3/hand-pattern.js').then((m) => m.handPatternCapability) },
];
