// ═══════════════════════════════════════════════════════════════
//  src/assembly/component-universe.gen.ts —— 运行时组件全集清单（生成物·勿手改）
//
//  由 `node scripts/build-component-map.mjs` 生成（确定性输出：升序去重·同输入同字节）。
//  来源 = src/engine/protocol/components/*.ts 全部组件 + src/skills/** 内 extends Component
//  的 skill 组件——即编译期闭集 ComponentDataMap（component-map.ts）的运行时可枚举对应物。
//  消费者：NON_DETERMINISTIC ⊆ 全集对账（determinism.test.ts）· 装配校验 · capability catalog。
//  加/改/删组件后同提交重跑生成命令；忘了 → scripts/build-component-map.test.mjs 漂移守卫亮红。
// ═══════════════════════════════════════════════════════════════

/** 全部运行时组件名（166 个·升序去重·生成物）。 */
export const COMPONENT_UNIVERSE = [
  'Acceleration',
  'Action',
  'Anim3D',
  'AnimState',
  'AnimState3D',
  'Armor',
  'Billboard3D',
  'BlockGrid',
  'BlockTrayPiece',
  'Blocker',
  'BoardCell',
  'Bounce',
  'Bounds',
  'Camera',
  'Camera3D',
  'CameraTarget',
  'CardPile',
  'Caster',
  'Clickable',
  'Coachmark',
  'Collider3D',
  'Color',
  'Controllable',
  'ConveyorQueue',
  'Cooldowns',
  'CraftRecipe',
  'DamageTable',
  'DebugTrace',
  'Decal3D',
  'DeliverDrop',
  'DestroyRequest',
  'DialogueAdvance',
  'DialogueChoose',
  'DialogueScript',
  'DicePool',
  'Diegetic3D',
  'Draggable',
  'DropZone',
  'DuelIntent',
  'DuelMatrix',
  'DuelOutcome',
  'Effect',
  'EventWhen',
  'FaceDir',
  'FaceRotate',
  'Facing',
  'Flag',
  'FlowAgent',
  'FlowField',
  'Fog3D',
  'Frame',
  'GameFlow',
  'Gauge',
  'Glow3D',
  'GridMover',
  'Grounded',
  'Group',
  'GroupCount',
  'HeldHand',
  'HexBoard',
  'HexPos',
  'Hierarchy',
  'Hitbox',
  'Impulse3D',
  'InputQueue',
  'IntentBarrier',
  'IntentInbox',
  'Inventory',
  'Joint3D',
  'KeyBinding',
  'Launch',
  'Light3D',
  'Line3D',
  'LineWins',
  'Mass',
  'MatchBoard',
  'Material3D',
  'Memory',
  'MemoryRules',
  'MergeDrop',
  'MergeEvent',
  'MergeProximity',
  'MergeRule',
  'Mesh3D',
  'Model3D',
  'ModifierSource',
  'ModifierTotals',
  'Mortal',
  'NavAgent',
  'NavGraph',
  'NavMesh',
  'NavPath',
  'Orbit',
  'Order',
  'OverTime',
  'Overlap',
  'Overlap3D',
  'Owner',
  'Path3D',
  'PathFollow',
  'PerCardRetrigger',
  'PerCardRule',
  'PerCardScore',
  'Perception',
  'PhysicsWorld3D',
  'Pickable3D',
  'Pivot3D',
  'PlaceBlockIntent',
  'PlayedHand',
  'PokerHand',
  'Post3D',
  'PrefabLibrary',
  'PrefabOrigin',
  'PullAnchor',
  'QueueMember',
  'QueueSlots',
  'RandomSeed',
  'RawInput',
  'Reflector3D',
  'Relation',
  'Resource',
  'ResourceModify',
  'RigidBody3D',
  'RolledDice',
  'ScoreTrace',
  'SelfRule',
  'Sensor',
  'Shape',
  'Signal',
  'Sky3D',
  'SlotMachine',
  'Sound',
  'SpatialIndex',
  'SpawnRequest',
  'Sprite',
  'StatBind',
  'State',
  'StateChanged',
  'Stats',
  'Status',
  'Steering',
  'StringSet',
  'StringVar',
  'Tag',
  'Text',
  'TextBinding',
  'Tilemap',
  'Timeline',
  'TimelinePlayback',
  'Timer',
  'TimerDone',
  'Trail3D',
  'Transform',
  'Transform3D',
  'Tray',
  'TraySeat',
  'Trigger',
  'TurnOrder',
  'Tween',
  'Velocity',
  'Vfx2D',
  'Vfx3D',
  'Visibility',
  'WeightedSpawn',
  'WorldUI3D',
  'Zone',
] as const;

/** 组件名字面量联合（生成物）。 */
export type RuntimeComponentName = (typeof COMPONENT_UNIVERSE)[number];

/** O(1) 成员查询视图（对账/校验用）。 */
export const COMPONENT_UNIVERSE_SET: ReadonlySet<string> = new Set(COMPONENT_UNIVERSE);
