import { defineCapability } from '@engine/core/define-capability.js';
import type { IWorld } from '@engine/core/types.js';
import type { MobilityLock, RelationOrbit, Transform, Velocity, State, FormChange, Resource, Shape, Perception, Steering } from '@engine/protocol/components.js';

/** Shared B3 mechanics. Every behavior is attached as data, never by unit id. */
export const mcfightB3Capability=defineCapability({
 id:'mcfight-b3-mechanics',version:'1.0.0',
 describe:{name:'MC Fight B3 mechanics',summary:'Non-hard-control mobility lock and steering-only target orbit.',semantic:['combat','mcfight','b3'],whenToUse:'Attach public data components; no unit-id branches.',examples:[]},
 components:{provides:{MobilityLock:{category:'effect',describe:'Refreshable movement lock without Flow cancellation.',fields:{}},RelationOrbit:{category:'config',describe:'Writes velocity only while a target relation is legal.',fields:{}},FormChange:{category:'effect',describe:'One-shot in-place data form projection.',fields:{}}},reads:['MobilityLock','RelationOrbit','Relation','Transform','Velocity','FormChange','Resource'],writes:['MobilityLock','Velocity','FormChange','Resource','Status','State','Shape','Steering','Perception'],consumes:[]},config:{},systems:[
 // MobilityLock is a final movement veto for this tick.  It intentionally runs
 // after every normal Velocity author (including optional probes) and before
 // motion integration: a lock must not be overwritten by ordinary steering.
 {id:'mcfight-mobility-lock',runsAfter:['flow','aggro','steering','path-follow','relation-orbit'],runsBefore:['motion-apply'],reads:['MobilityLock','Velocity','Status'],writes:['MobilityLock','Velocity','Status'],consumes:[],execute(world:IWorld){const now=world.getVersion();for(const [id] of world.query('MobilityLock')){const lock=world.getComponent<MobilityLock>(id,'MobilityLock')!;let status=world.getComponent<any>(id,'Status');if(lock.untilTick<=now){if(status&&lock.groundWhileLocked){if(lock.originalAir)status.flags|=4;else status.flags&=~4;if(lock.originalGround)status.flags|=8;else status.flags&=~8;}world.removeComponent(id,'MobilityLock');continue;}if(lock.groundWhileLocked&&status){status.flags&=~4;status.flags|=8;}let v=world.getComponent<Velocity>(id,'Velocity');if(!v){world.addComponent(id,{type:'Velocity',vx:0,vy:0,angular:0} as Velocity);v=world.getComponent<Velocity>(id,'Velocity')!;}v.vx=0;v.vy=0;}}},
 {id:'relation-orbit',runsAfter:['flow','aggro','steering','path-follow'],runsBefore:['mcfight-mobility-lock','motion-apply'],reads:['RelationOrbit','Relation','Transform','Velocity','State'],writes:['Velocity'],consumes:[],execute(world:IWorld){for(const [id] of world.query('RelationOrbit','Transform')){const o=world.getComponent<RelationOrbit>(id,'RelationOrbit')!,t=world.getComponent<Transform>(id,'Transform')!,state=world.getComponent<State>(id,'State');if(!o.active||state?.current!=='Free')continue;const rel=world.getComponent<any>(id,'Relation');const target=rel?.kind==='target'?world.getComponent<Transform>(rel.targetId,'Transform'):undefined;if(!target){const v=world.getComponent<Velocity>(id,'Velocity');if(v){v.vx=0;v.vy=0;}continue;}const dx=t.x-target.x,dy=t.y-target.y,d=Math.hypot(dx,dy);if(!d)continue;let v=world.getComponent<Velocity>(id,'Velocity');if(!v){world.addComponent(id,{type:'Velocity',vx:0,vy:0,angular:0} as Velocity);v=world.getComponent<Velocity>(id,'Velocity')!;}const sign=o.clockwise?-1:1, radial=Math.max(-1,Math.min(1,(d-o.radius)/Math.max(o.radius,1e-6)));const tx=-dy/d*sign,ty=dx/d*sign,rx=-dx/d*radial,ry=-dy/d*radial;const n=Math.hypot(tx+rx,ty+ry)||1;v.vx=(tx+rx)/n*o.speed;v.vy=(ty+ry)/n*o.speed;}}},
 {id:'form-change',runsAfter:['resource-apply'],runsBefore:['aggro','flow'],reads:['FormChange','Resource'],writes:['FormChange','Resource','Status','State','Shape','Steering','Perception'],consumes:[],execute(world:IWorld){for(const [id] of world.query('FormChange','Resource')){const f=world.getComponent<FormChange>(id,'FormChange')!,r=world.getComponent<Resource>(id,'Resource')!;if(f.changed||r.max<=0||r.current/r.max>f.threshold)continue;const ratio=r.current/r.max;if(f.formMaxHp!==undefined){r.max=f.formMaxHp;r.current=Math.max(r.min,Math.min(r.max,r.max*ratio));}if(f.formSpeed!==undefined){const steer=world.getComponent<Steering>(id,'Steering');if(steer)steer.speed=f.formSpeed;}if(f.formRadius!==undefined){const shape=world.getComponent<Shape>(id,'Shape');if(shape?.kind==='circle')shape.radius=f.formRadius;}if(f.formAirborne!==undefined){let st=world.getComponent<any>(id,'Status');if(!st){world.addComponent(id,{type:'Status',flags:0} as any);st=world.getComponent<any>(id,'Status')!;}if(f.formAirborne){st.flags|=4;st.flags&=~8;}else{st.flags|=8;st.flags&=~4;}}if(f.formPerceptionRejectStatusMask!==undefined){const p=world.getComponent<Perception>(id,'Perception');if(p)p.targetCheck={...(p.targetCheck??{}),rejectStatusMask:f.formPerceptionRejectStatusMask};}const state=f.formStateEntity?world.getComponent<State>(f.formStateEntity,'State'):undefined;if(state){state.previous=state.current;state.current=f.formId;}f.changed=true;}}},
 ]
});

